[build-system]
requires = ["setuptools>=40.8.0", "wheel", "pybind11-stubgen", "ruff", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "poselib"
dynamic = ["version"]
description = "RANSAC + collection of minimal solvers for camera pose estimation."
authors = [
    {name = "Viktor Larsson and contributors", email = "viktor.larsson@math.lth.se"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
test = [
    "posebench @ git+https://github.com/Parskatt/posebench.git#egg=posebench; python_version <= '3.13'",
]

[tool.cibuildwheel]
test-extras = ["test"]
test-command = '''
python -c "
import sys
if sys.version_info <= (3, 13):
    import subprocess
    subprocess.run(['posebench', '--subsample', '100'], check=True)
else:
    print('Python > 3.13: Running simple import test due to deps not ready yet')
    import poselib
    print('Import successful for Python > 3.13')
"
'''