name: Build

on: 
  push:
    branches:    
      - master
  release:
    types: [published]

env:
  BUILD_CONFIGURATION: Release
  BUILD_DIR: _build
  INSTALL_DIR: _install

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: CMAKE_INSTALL_PREFIX=${{github.workspace}}/${{env.INSTALL_DIR}}          
          CIBW_BEFORE_ALL_LINUX: yum install -y eigen3-devel
          CIBW_ARCHS_LINUX: "native"
          
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg --triplet x64-windows install eigen3
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"

          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_ARCHS_MACOS: "arm64 x86_64"
          CIBW_SKIP: "*-musllinux_x86_64"
          CIBW_BEFORE_TEST: echo test out
          CIBW_TEST_COMMAND:
            ls -la /home/runner/.cache/cibuildwheel
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
