name: Build

on: 
  push:
    branches:    
      - dev
  release:
    types: [published]
    
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y eigen3-devel
          CIBW_ARCHS_LINUX: "native"
          # I don't know how to compile on windows, please help
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg install eigen3
          CIBW_ENVIRONMENT_WINDOWS: $env:CMAKE_TOOLCHAIN_FILE = "C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"

          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_ARCHS_MACOS: "native"
          
          CIBW_SKIP: "*-musllinux_x86_64"
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_all:
    needs: [build_wheels]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
