name: Build

on: 
  push:
    branches:    
      - master
  release:
    types: [published]
    
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Python 3.8 Universal2 for Apple Silicon 
        if: matrix.os == 'macos-14'
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.1
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
          CIBW_ENVIRONMENT: BUILD_SHARED_LIBS="OFF" 
          CIBW_BEFORE_ALL_LINUX: yum install -y eigen3-devel
          CIBW_ARCHS_LINUX: "native"
          
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg --triplet x64-windows install eigen3
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"
          
          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_ARCHS_MACOS: "universal2"
          CIBW_SKIP: "*-musllinux_x86_64"
          CIBW_TEST_COMMAND: >
            python -c "import poselib"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl