name: Build

on: 
  push:
    branches:    
      - master
  release:
    types: [published]
    
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: BUILD_SHARED_LIBS="OFF" 
          
          CIBW_BEFORE_ALL_LINUX: yum install -y eigen3-devel
          CIBW_ARCHS_LINUX: "native"
          
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg --triplet x64-windows install eigen3
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"

          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_SKIP: "*-musllinux_x86_64"
          CIBW_TEST_COMMAND: >
            python -c "import poselib"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
