name: Build

on: 
  push:
    branches:    
      - master
  release:
    types: [published]
    
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Python 3.8 Universal2 for Apple Silicon 
        if: matrix.os == 'macos-14'
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0
        env:
          CIBW_ENVIRONMENT: BUILD_SHARED_LIBS="OFF" 
          
          CIBW_BEFORE_ALL_LINUX: apt-get update && apt-get install -y libeigen3-dev
          CIBW_ARCHS_LINUX: "native"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24 # https://cibuildwheel.pypa.io/en/stable/options/#linux-image, https://github.com/pypa/cibuildwheel/blob/bd033a44476646b606efccdd5eed92d5ea1d77ad/docs/faq.md?plain=1#L13
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg --triplet x64-windows install eigen3
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"
          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_SKIP: "*-musllinux_x86_64 pp3*"
          CIBW_TEST_COMMAND: >
            python -c "import poselib"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
